import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import cron from 'node-cron';
import QRCode from 'qrcode';
import pino from 'pino';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { Boom } from '@hapi/boom';
import makeWASocket, { DisconnectReason, fetchLatestBaileysVersion, useMultiFileAuthState, makeCacheableSignalKeyStore } from '@whiskeysockets/baileys';
import puppeteer from 'puppeteer';
import nodemailer from 'nodemailer';
import pg from 'pg';
const { Pool } = pg;

const app=express();
const PORT=Number(process.env.PORT||3000), TZ=process.env.TZ||'America/Sao_Paulo';
const API_TOKEN=process.env.API_TOKEN||'';
const MASTER_LOGIN=(process.env.MASTER_LOGIN||process.env.MASTER_EMAIL||'').trim().toLowerCase();
const MASTER_PASSWORD=process.env.MASTER_PASSWORD||'';
const JWT_SECRET=process.env.JWT_SECRET||API_TOKEN||'change-this-secret';
const ROOT=path.resolve(process.env.DATA_DIR||((fs.existsSync('/data'))?'/data/ofertazap':'./data'));
const AUTH_ROOT=path.resolve(process.env.BAILEYS_AUTH_ROOT||path.join(ROOT,'clientes'));
fs.mkdirSync(ROOT,{recursive:true});fs.mkdirSync(AUTH_ROOT,{recursive:true});
const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL, ssl: String(process.env.DATABASE_SSL||'true') === 'true' ? { rejectUnauthorized: false } : false, max: Number(process.env.PG_POOL_MAX||10) }) : null;
let dbReady=false;
app.use(cors({origin:process.env.FRONTEND_ORIGIN||'*'}));app.use(express.json({limit:'6mb'}));
const files={db:path.join(ROOT,'saas.json'),products:path.join(ROOT,'products.json'),jobs:path.join(ROOT,'jobs.json'),groups:path.join(ROOT,'groups.json'),templates:path.join(ROOT,'templates.json'),logs:path.join(ROOT,'logs.json')};
const mailer=(process.env.SMTP_HOST&&process.env.SMTP_USER&&process.env.SMTP_PASS)?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}):null;
async function sendCodeEmail(to,code,type){if(!mailer){console.log(`[EMAIL TEST] ${type} para ${to}: ${code}`);return false}await mailer.sendMail({from:process.env.SMTP_FROM||process.env.SMTP_USER,to,subject:type==='verification'?'OfertaZap — confirme seu e-mail':'OfertaZap — recuperação de senha',text:`Seu código OfertaZap é: ${code}. Ele expira em 15 minutos.`});return true}

function load(f,d){try{return fs.existsSync(f)?JSON.parse(fs.readFileSync(f,'utf8')):d}catch{return d}}
const defaultDb={users:[],plans:[{id:'p1',name:'Plano 1',limit:200,price:29.9},{id:'p2',name:'Plano 2',limit:300,price:49.9},{id:'p3',name:'Plano 3',limit:700,price:79.9}],subscriptions:[],settings:{brand:'OfertaZap'}};
const defaultTemplates=[
{id:'t1',name:'🔥 Oferta imperdível',text:'🔥 OFERTA IMPERDÍVEL!\n\n📦 {produto}\n💰 De {preco_antigo} por {preco}\n🏷️ {desconto} OFF\n\n👉 Comprar agora:\n{link}'},
{id:'t2',name:'🚨 Corre que pode acabar',text:'🚨 CORRE QUE PODE ACABAR!\n\n🛍️ {produto}\n💰 {preco}\n\n🔥 Aproveite enquanto está disponível!\n\n👇 {link}'},
{id:'t3',name:'💥 Promoção do dia',text:'💥 PROMOÇÃO DO DIA!\n\n{produto}\n🔥 {preco}\n🏷️ {desconto} OFF\n\n👉 Confira:\n{link}'}];
let db=load(files.db,defaultDb),products=load(files.products,[]),jobs=load(files.jobs,[]),groups=load(files.groups,[]),templates=load(files.templates,defaultTemplates),logs=load(files.logs,[]);
const wa=new Map();
function snapshot(){return {db,products,jobs,groups,templates,logs};}
async function persistState(){if(!pool)return;await pool.query(`INSERT INTO app_state(id,state,updated_at) VALUES(1,$1::jsonb,NOW()) ON CONFLICT(id) DO UPDATE SET state=EXCLUDED.state,updated_at=NOW()`,[JSON.stringify(snapshot())]);}
function save(f,d){const t=f+'.tmp';fs.writeFileSync(t,JSON.stringify(d,null,2));fs.renameSync(t,f);if(dbReady&&pool)persistState().catch(e=>console.error('PostgreSQL:',e.message));}
async function initPersistence(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS app_state(id INTEGER PRIMARY KEY,state JSONB NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);const r=await pool.query('SELECT state FROM app_state WHERE id=1');if(r.rows[0]?.state){const x=r.rows[0].state;db=x.db||defaultDb;products=x.products||[];jobs=x.jobs||[];groups=x.groups||[];templates=x.templates||defaultTemplates;logs=x.logs||[];save(files.db,db);save(files.products,products);save(files.jobs,jobs);save(files.groups,groups);save(files.templates,templates);save(files.logs,logs);console.log('PostgreSQL carregado: dados restaurados.')}else{await persistState();console.log('PostgreSQL inicializado: dados JSON migrados.')}dbReady=true;}
function log(action,userId,meta={}){logs.unshift({id:crypto.randomUUID(),at:new Date().toISOString(),action,userId,meta});logs=logs.slice(0,2000);save(files.logs,logs)}
function ensureMaster(){if(!MASTER_LOGIN||!MASTER_PASSWORD)throw Error('MASTER_LOGIN e MASTER_PASSWORD precisam estar configurados nas variáveis do Render.');let u=db.users.find(x=>x.role==='MASTER');if(!u){const salt=crypto.randomBytes(16).toString('hex');db.users.push({id:'master',role:'MASTER',name:'Administrador Master',email:MASTER_LOGIN,passwordHash:hash(MASTER_PASSWORD,salt),salt,active:true,createdAt:new Date().toISOString()});save(files.db,db)}else if(u.email!==MASTER_LOGIN){u.email=MASTER_LOGIN;const salt=crypto.randomBytes(16).toString('hex');u.passwordHash=hash(MASTER_PASSWORD,salt);u.salt=salt;u.active=true;save(files.db,db)}}
function hash(p,s){return crypto.scryptSync(String(p),s,64).toString('hex')}
function verify(p,u){return crypto.timingSafeEqual(Buffer.from(hash(p,u.salt),'hex'),Buffer.from(u.passwordHash,'hex'))}
function b64(v){return Buffer.from(JSON.stringify(v)).toString('base64url')}
function token(user){const h=b64({alg:'HS256',typ:'JWT'}),p=b64({sub:user.id,role:user.role,iat:Date.now()});const sig=crypto.createHmac('sha256',JWT_SECRET).update(h+'.'+p).digest('base64url');return h+'.'+p+'.'+sig}
function auth(req,res,next){try{const x=(req.headers.authorization||'').replace(/^Bearer\s+/,'');if(!x)throw Error('Token ausente');const [h,p,s]=x.split('.');const ok=crypto.timingSafeEqual(Buffer.from(s||''),Buffer.from(crypto.createHmac('sha256',JWT_SECRET).update(h+'.'+p).digest('base64url')));if(!ok)throw Error('Token inválido');const payload=JSON.parse(Buffer.from(p,'base64url'));const u=db.users.find(x=>x.id===payload.sub&&x.active!==false);if(!u)throw Error('Usuário inválido');req.user=u;next()}catch(e){res.status(401).json({error:'Não autorizado'})}}
function master(req,res,next){if(req.user.role!=='MASTER')return res.status(403).json({error:'Somente administrador Master'});next()}
function client(req,res,next){if(!['CLIENT','MASTER'].includes(req.user.role))return res.status(403).json({error:'Acesso negado'});next()}
function subOf(uid){return db.subscriptions.find(s=>s.userId===uid)}
function activeSub(uid){const s=subOf(uid);return s&&s.status==='active'&&new Date(s.expiresAt)>new Date()?s:null}
function jobProductIds(j){return Array.isArray(j?.productIds)?j.productIds.filter(Boolean):(j?.productId?[j.productId]:[])}
function quota(uid){const s=activeSub(uid);if(!s)return {limit:0,used:0,remaining:0};const plan=db.plans.find(p=>p.id===s.planId)||db.plans[0];const used=new Set();for(const j of jobs.filter(j=>j.userId===uid&&j.enabled!==false))for(const id of jobProductIds(j))used.add(id);return {limit:Number(plan.limit)||0,used:used.size,remaining:Math.max(0,(Number(plan.limit)||0)-used.size)}}
function assertQuota(uid,productIds){const q=quota(uid);const current=new Set();for(const j of jobs.filter(j=>j.userId===uid&&j.enabled!==false))for(const id of jobProductIds(j))current.add(id);for(const id of productIds||[])if(id)current.add(id);if(current.size>q.limit)throw Error(`Limite do plano atingido: ${q.limit} produtos na agenda.`)}
function money(n){return n==null?'':Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function discount(old,p){return old&&p&&old>p?Math.round((1-p/old)*100)+'%':''}
function itemIds(v){return [...new Set((String(v||'').match(/\bMLB[-_]?\d{6,}\b/gi)||[]).map(x=>x.replace(/[-_]/g,'').toUpperCase()))]}
async function mlItem(id){const r=await fetch('https://api.mercadolibre.com/items/'+encodeURIComponent(id));if(!r.ok)throw Error('Produto Mercado Livre não encontrado');return r.json()}
async function resolveML(link){const direct=itemIds(link);for(const id of direct){try{return await mlItem(id)}catch{}}
let candidates=[link],seen=new Set();const add=x=>{try{if(x&&!seen.has(x)){seen.add(x);candidates.push(new URL(x,link).toString())}}catch{}};
for(let n=0;n<10&&candidates.length;n++){const u=candidates[n];try{const r=await fetch(u,{redirect:'manual',headers:{'user-agent':'Mozilla/5.0','accept-language':'pt-BR,pt;q=0.9'}});const txt=await r.text();const ids=itemIds((r.headers.get('location')||'')+'\n'+txt);for(const id of ids){try{return await mlItem(id)}catch{}};add(r.headers.get('location'));for(const m of txt.matchAll(/(?:canonical|og:url|twitter:url)[^>]+(?:content|href)=["']([^"']+)/gi))add(m[1]);}catch{}}
if(/^https?:\/\/(www\.)?meli\.la/i.test(link)){let browser;try{browser=await puppeteer.launch({headless:true,args:['--no-sandbox','--disable-setuid-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage();await page.setViewport({width:390,height:844,isMobile:true});await page.goto(link,{waitUntil:'domcontentloaded',timeout:25000});try{await page.waitForNetworkIdle({idleTime:800,timeout:8000})}catch{}const data=await page.evaluate(()=>({url:location.href,html:document.documentElement.outerHTML}));for(const id of itemIds(data.url+'\n'+data.html)){try{return await mlItem(id)}catch{}}}finally{if(browser)await browser.close()}}
throw Error('Não consegui identificar o anúncio Mercado Livre neste link.')}


ensureMaster();
app.get('/api/health',(_,res)=>res.json({ok:true,service:'OfertaZap SaaS V32',time:new Date().toISOString()}));
app.get('/api/config/public',(_,res)=>res.json({ok:true,brand:db.settings.brand,plans:db.plans.map(({id,name,limit,price})=>({id,name,limit,price}))}));
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password,company,phone}=req.body||{};if(!name||!email||!password||!phone)throw Error('Nome, e-mail, senha e celular são obrigatórios');const cleanPhone=String(phone).replace(/\D/g,'');if(cleanPhone.length<10||cleanPhone.length>15)throw Error('Número de celular inválido');const e=email.toLowerCase().trim();if(db.users.some(u=>u.email===e))throw Error('E-mail já cadastrado');const salt=crypto.randomBytes(16).toString('hex'),id=crypto.randomUUID();db.users.push({id,role:'CLIENT',name,email:e,company:company||'',phone:cleanPhone,passwordHash:hash(password,salt),salt,active:true,emailVerified:true,createdAt:new Date().toISOString()});save(files.db,db);log('client_registered',id);res.json({ok:true,message:'Cadastro criado com sucesso. Você já pode entrar.',verificationRequired:false})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/auth/login',(req,res)=>{const {email,password}=req.body||{},u=db.users.find(x=>x.email===String(email||'').toLowerCase());if(!u||!verify(password||'',u)||u.active===false)return res.status(401).json({error:'E-mail ou senha inválidos'});log('login',u.id);res.json({ok:true,token:token(u),user:{id:u.id,role:u.role,name:u.name,email:u.email,company:u.company}})});
app.post('/api/auth/forgot',(req,res)=>{const u=db.users.find(x=>x.email===String(req.body?.email||'').toLowerCase());if(u){u.resetCode=String(Math.floor(100000+Math.random()*900000));u.resetExpires=Date.now()+15*60*1000;save(files.db,db);sendCodeEmail(u.email,u.resetCode,'reset').catch(e=>console.error('EMAIL',e.message))}res.json({ok:true,message:'Se o e-mail existir, um código foi enviado.'})});
app.post('/api/auth/reset',(req,res)=>{const {email,code,password}=req.body||{},u=db.users.find(x=>x.email===String(email||'').toLowerCase());if(!u||u.resetCode!==String(code||'')||Date.now()>u.resetExpires)return res.status(400).json({error:'Código inválido ou expirado'});const salt=crypto.randomBytes(16).toString('hex');u.salt=salt;u.passwordHash=hash(password,salt);u.resetCode=null;save(files.db,db);res.json({ok:true})});

app.use('/api',auth);
app.get('/api/me',(req,res)=>{const s=subOf(req.user.id),q=quota(req.user.id);res.json({user:{id:req.user.id,role:req.user.role,name:req.user.name,email:req.user.email,company:req.user.company,brand:req.user.brand,color:req.user.color,logo:req.user.logo},subscription:s,quota:q})});
app.patch('/api/client/settings',(req,res)=>{const u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:'Usuário não encontrado'});u.company=req.body.company??u.company;u.brand=req.body.brand??u.brand;u.color=req.body.color??u.color;u.logo=req.body.logo??u.logo;save(files.db,db);log('client_customized',req.user.id);res.json({ok:true,user:{company:u.company,brand:u.brand,color:u.color,logo:u.logo}})});

app.get('/api/dashboard',(req,res)=>{const ps=products.filter(p=>p.userId===req.user.id),js=jobs.filter(j=>j.userId===req.user.id),gs=groups.filter(g=>g.userId===req.user.id);const w=wa.get(req.user.id);res.json({products:ps.length,jobs:js.length,groups:gs.length,whatsapp:w?.state||'disconnected',quota:quota(req.user.id),sent:js.reduce((n,j)=>n+(j.sentCount||0),0),pending:js.filter(j=>j.status==='pending'&&j.enabled!==false).length,errors:js.filter(j=>j.status==='error').length})});

// MASTER
app.get('/api/master/overview',master,(req,res)=>res.json({users:db.users.filter(u=>u.role==='CLIENT').map(u=>{const s=subOf(u.id);return {id:u.id,name:u.name,email:u.email,company:u.company,active:u.active!==false,subscription:s||null,quota:quota(u.id),whatsapp:wa.get(u.id)?.state||'disconnected'}}),plans:db.plans,logs:logs.slice(0,100)}));
app.post('/api/master/clients',master,(req,res)=>{try{const {name,email,password,company,phone,planId}=req.body||{};if(!name||!email||!password)throw Error('Dados obrigatórios');const cleanPhone=String(phone||'').replace(/\D/g,'');const e=email.toLowerCase().trim();if(db.users.some(u=>u.email===e))throw Error('E-mail já cadastrado');const salt=crypto.randomBytes(16).toString('hex'),id=crypto.randomUUID();db.users.push({id,role:'CLIENT',name,email:e,company:company||'',phone:cleanPhone,passwordHash:hash(password,salt),salt,active:true,emailVerified:true,createdAt:new Date().toISOString()});const plan=db.plans.find(p=>p.id===planId)||db.plans[0];db.subscriptions.push({id:crypto.randomUUID(),userId:id,planId:plan.id,status:'active',startedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+30*864e5).toISOString(),paymentId:'MASTER'});save(files.db,db);log('master_created_client',req.user.id,{clientId:id});res.json({ok:true,id})}catch(e){res.status(400).json({error:e.message})}});
app.patch('/api/master/clients/:id',master,(req,res)=>{const u=db.users.find(x=>x.id===req.params.id&&x.role==='CLIENT');if(!u)return res.status(404).json({error:'Cliente não encontrado'});Object.assign(u,req.body||{});save(files.db,db);log('master_updated_client',req.user.id,{clientId:u.id});res.json({ok:true})});
app.post('/api/master/clients/:id/renew',master,(req,res)=>{const u=db.users.find(x=>x.id===req.params.id&&x.role==='CLIENT');if(!u)return res.status(404).json({error:'Cliente não encontrado'});const s=subOf(u.id)||{id:crypto.randomUUID(),userId:u.id};const start=new Date();const base=new Date(s.expiresAt)>start?new Date(s.expiresAt):start;s.status='active';s.startedAt=start.toISOString();s.expiresAt=new Date(base.getTime()+30*864e5).toISOString();s.paymentId=req.body?.paymentId||'MANUAL';if(!subOf(u.id))db.subscriptions.push(s);u.active=true;save(files.db,db);log('master_renewed_client',req.user.id,{clientId:u.id});res.json({ok:true,subscription:s})});
app.post('/api/master/clients/:id/suspend',master,(req,res)=>{const u=db.users.find(x=>x.id===req.params.id&&x.role==='CLIENT');if(!u)return res.status(404).json({error:'Cliente não encontrado'});u.active=false;const s=subOf(u.id);if(s)s.status='suspended';save(files.db,db);log('master_suspended_client',req.user.id,{clientId:u.id});res.json({ok:true})});
app.post('/api/master/assume/:id',master,(req,res)=>{const u=db.users.find(x=>x.id===req.params.id&&x.role==='CLIENT');if(!u)return res.status(404).json({error:'Cliente não encontrado'});log('master_assume_client',req.user.id,{clientId:u.id});res.json({ok:true,token:token(u),user:{id:u.id,role:'CLIENT',name:u.name,email:u.email,company:u.company}})});
app.get('/api/master/logs',master,(req,res)=>res.json({logs}));
app.patch('/api/master/plans/:id',master,(req,res)=>{const p=db.plans.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:'Plano não encontrado'});Object.assign(p,{name:req.body.name??p.name,limit:Number(req.body.limit??p.limit),price:Number(req.body.price??p.price)});save(files.db,db);res.json({ok:true,plan:p})});

// CLIENT DATA
app.get('/api/products',(req,res)=>res.json({products:products.filter(p=>p.userId===req.user.id)}));
function normalizeMoney(v){const raw=String(v??'').trim().replace(/R\$\s?/gi,'').replace(/\./g,'').replace(',','.');if(raw==='')return '';const n=Number(raw);return Number.isFinite(n)?n.toFixed(2):''}
function validateProductBody(b){if(!b.name)throw Error('Nome do produto é obrigatório');const price=normalizeMoney(b.price);if(!price||Number(price)<=0)throw Error('Informe um valor válido para o produto');if(!b.link)throw Error('Informe o link da oferta');const imageData=String(b.imageData||'');if(imageData&&imageData.length>4500000)throw Error('Imagem muito grande. Escolha uma imagem menor.');const imageUrl=String(b.imageUrl||'').trim();return {name:String(b.name).trim(),price,oldPrice:normalizeMoney(b.oldPrice),discount:String(b.discount||'').trim(),category:String(b.category||'').trim(),link:String(b.link).trim(),message:String(b.message||''),imageData,imageUrl}}
app.post('/api/products',(req,res)=>{try{const b=validateProductBody(req.body||{});const p={id:crypto.randomUUID(),userId:req.user.id,createdAt:new Date().toISOString(),...b,active:true};products.push(p);save(files.products,products);log('product_created',req.user.id,{productId:p.id});res.json({ok:true,product:p,message:'Produto salvo com sucesso.'})}catch(e){res.status(400).json({error:e.message})}});
app.patch('/api/products/:id',(req,res)=>{try{const p=products.find(x=>x.id===req.params.id&&x.userId===req.user.id);if(!p)return res.status(404).json({error:'Produto não encontrado'});const b={...p,...req.body};const v=validateProductBody(b);Object.assign(p,v);save(files.products,products);log('product_updated',req.user.id,{productId:p.id});res.json({ok:true,product:p,message:'Produto atualizado com sucesso.'})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/products/:id',(req,res)=>{products=products.filter(x=>!(x.id===req.params.id&&x.userId===req.user.id));save(files.products,products);res.json({ok:true})});
app.post('/api/products/preview',async(req,res)=>{try{const d=await resolveML(req.body?.link);const price=d.price;const old=d.original_price||d.original_price||null;res.json({ok:true,product:{id:d.id,title:d.title,price,oldPrice:old,discount:discount(old,price),image:d.pictures?.[0]?.url||d.thumbnail,permalink:d.permalink}})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/templates',(req,res)=>{const builtins=templates.filter(t=>!t.userId);const mine=templates.filter(t=>t.userId===req.user.id);res.json({templates:[...builtins,...mine]})});
app.post('/api/templates',(req,res)=>{const name=String(req.body?.name||'').trim(),text=String(req.body?.text||'').trim();if(!name||!text)return res.status(400).json({error:'Nome e mensagem são obrigatórios'});const t={id:crypto.randomUUID(),userId:req.user.id,name,text,createdAt:new Date().toISOString()};templates.push(t);save(files.templates,templates);res.json({ok:true,template:t})});
app.delete('/api/templates/:id',(req,res)=>{const i=templates.findIndex(t=>t.id===req.params.id&&t.userId===req.user.id);if(i<0)return res.status(404).json({error:'Modelo não encontrado'});templates.splice(i,1);save(files.templates,templates);res.json({ok:true})});
app.get('/api/groups',(req,res)=>res.json({groups:groups.filter(g=>g.userId===req.user.id)}));
function extractInviteCode(value){const m=String(value||'').match(/chat\.whatsapp\.com\/([A-Za-z0-9_-]+)/i);return m?.[1]||null}
app.post('/api/groups',async(req,res)=>{try{const name=String(req.body?.name||'').trim(),inviteLink=String(req.body?.inviteLink||'').trim(),jid=String(req.body?.jid||'').trim();if(!name)throw Error('Informe o nome do grupo');if(!inviteLink&&!jid)throw Error('Informe o link de convite do grupo');let groupJid=jid||'',groupName=name;const x=wa.get(req.user.id);if(!groupJid&&inviteLink&&x?.sock){const code=extractInviteCode(inviteLink);if(!code)throw Error('Link de convite inválido');try{const info=await x.sock.groupGetInviteInfo(code);groupJid=info.id;groupName=name||info.subject||groupName}catch(e){throw Error('Não foi possível identificar o grupo pelo link: '+e.message)}}const duplicate=groups.find(g=>g.userId===req.user.id&&((groupJid&&g.jid===groupJid)||(inviteLink&&g.inviteLink===inviteLink)));if(duplicate)return res.status(409).json({error:'Este grupo já está cadastrado.'});const g={id:crypto.randomUUID(),userId:req.user.id,name:groupName,jid:groupJid,inviteLink:inviteLink||'',enabled:true,status:groupJid?'connected':'pending',createdAt:new Date().toISOString()};groups.push(g);save(files.groups,groups);res.json({ok:true,group:g,message:groupJid?'Grupo vinculado com sucesso.':'Grupo salvo. Será vinculado quando o WhatsApp estiver conectado.'})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/whatsapp/status',(req,res)=>{const x=wa.get(req.user.id)||{};res.json({state:x.state||'disconnected',connected:x.state==='connected',qrAvailable:Boolean(x.qr),groups:groups.filter(g=>g.userId===req.user.id).length,lastError:x.lastError||null})});
app.get('/api/whatsapp/qr',async(req,res)=>{const x=wa.get(req.user.id);if(!x?.qr)return res.status(404).json({error:'QR ainda não disponível'});res.json({ok:true,qr:x.qr})});
async function startWA(uid,opts={}){let x=wa.get(uid)||{state:'disconnected'};if(x.state==='connecting'||x.state==='connected')return x;const dir=path.join(AUTH_ROOT,uid);fs.mkdirSync(dir,{recursive:true});x={state:'connecting',qr:null,pairingCode:null,lastError:null};wa.set(uid,x);const {state,saveCreds}=await useMultiFileAuthState(dir);const {version}=await fetchLatestBaileysVersion();const sock=makeWASocket({version,logger:pino({level:'silent'}),auth:{creds:state.creds,keys:makeCacheableSignalKeyStore(state.keys,pino({level:'silent'}))},printQRInTerminal:false,browser:['OfertaZap','Chrome','1.0.0']});x.sock=sock;sock.ev.on('creds.update',saveCreds);sock.ev.on('connection.update',async({connection,lastDisconnect,qr})=>{if(qr&&!opts.pairing)x.qr=await QRCode.toDataURL(qr);if(connection==='open'){x.state='connected';x.qr=null;x.pairingCode=null;x.lastError=null;try{const all=await sock.groupFetchAllParticipating();const own=groups.filter(g=>g.userId===uid);for(const [jid,g] of Object.entries(all)){let item=own.find(z=>z.jid===jid);if(item){item.name=item.name||g.subject||jid;item.status='connected';item.enabled=true}else{item={id:crypto.randomUUID(),userId:uid,name:g.subject||jid,jid,inviteLink:'',enabled:true,status:'connected'};groups.push(item)}}for(const item of own.filter(g=>!g.jid&&g.inviteLink)){try{const code=extractInviteCode(item.inviteLink);if(!code)continue;const info=await sock.groupGetInviteInfo(code);item.jid=info.id;item.name=item.name||info.subject||'Grupo WhatsApp';item.status='connected'}catch{}}save(files.groups,groups)}catch{};log('whatsapp_connected',uid)}if(connection==='close'){x.state='disconnected';x.qr=null;x.pairingCode=null;x.lastError=String(new Boom(lastDisconnect?.error)?.output?.statusCode||lastDisconnect?.error?.message||'Conexão encerrada');if(Number(new Boom(lastDisconnect?.error)?.output?.statusCode)!==DisconnectReason.loggedOut)setTimeout(()=>startWA(uid).catch(()=>{}),5000)}});return x}
function cleanPhone(v){return String(v||'').replace(/\D/g,'')}
app.get('/api/whatsapp/status',(req,res)=>{const x=wa.get(req.user.id)||{};res.json({state:x.state||'disconnected',connected:x.state==='connected',qrAvailable:Boolean(x.qr),pairingAvailable:x.state==='connecting'||x.state==='disconnected',groups:groups.filter(g=>g.userId===req.user.id).length,lastError:x.lastError||null,authPersistent:fs.existsSync(path.join(AUTH_ROOT,req.user.id,'creds.json'))})});
app.get('/api/whatsapp/qr',async(req,res)=>{const x=wa.get(req.user.id);if(!x?.qr)return res.status(404).json({error:'QR ainda não disponível. Se a sessão já estiver salva, não é necessário QR.'});res.json({ok:true,qr:x.qr})});
app.post('/api/whatsapp/pairing-code',async(req,res)=>{try{const phone=cleanPhone(req.body?.phone);if(!/^55?\d{10,13}$/.test(phone))throw Error('Informe o número com DDI. Ex.: 5566999999999');let x=wa.get(req.user.id);if(x?.state==='connected')return res.json({ok:true,connected:true,message:'WhatsApp já está conectado.'});if(!x||x.state!=='connecting')x=await startWA(req.user.id,{pairing:true});const code=await x.sock.requestPairingCode(phone);x.pairingCode=code;res.json({ok:true,code,state:x.state})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/whatsapp/restart-session',async(req,res)=>{try{const uid=req.user.id,x=wa.get(uid);try{await x?.sock?.logout()}catch{};wa.delete(uid);const dir=path.join(AUTH_ROOT,uid);fs.rmSync(dir,{recursive:true,force:true});await startWA(uid);res.json({ok:true,state:wa.get(uid)?.state||'connecting',qrAvailable:Boolean(wa.get(uid)?.qr)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/whatsapp/start',async(req,res)=>{try{const x=await startWA(req.user.id);res.json({ok:true,state:x.state,qrAvailable:Boolean(x.qr)})}catch(e){res.status(400).json({error:e.message})}});
app.post('/api/whatsapp/disconnect',async(req,res)=>{const x=wa.get(req.user.id);try{await x?.sock?.logout()}catch{};if(x)x.state='disconnected';res.json({ok:true})});

function renderMsg(t,p){return String(t||'').replaceAll('{produto}',p.name||'Produto').replaceAll('{preco}',money(p.price)).replaceAll('{preco_antigo}',money(p.oldPrice)).replaceAll('{desconto}',p.discount||discount(Number(p.oldPrice),Number(p.price))||'').replaceAll('{link}',p.link||'')}
app.get('/api/jobs',(req,res)=>res.json({jobs:jobs.filter(j=>j.userId===req.user.id),quota:quota(req.user.id)}));
app.post('/api/jobs',(req,res)=>{try{if(!activeSub(req.user.id))throw Error('Assinatura vencida ou inativa. Escolha/ative um plano para agendar.');const productIds=[...new Set((Array.isArray(req.body.productIds)?req.body.productIds:[req.body.productId]).filter(Boolean).map(String))];const groupIds=[...new Set((Array.isArray(req.body.groupIds)?req.body.groupIds:[req.body.groupId]).filter(Boolean).map(String))];if(!productIds.length)throw Error('Selecione ou cadastre pelo menos um produto.');if(!groupIds.length)throw Error('Selecione pelo menos um grupo.');const ownProducts=products.filter(p=>p.userId===req.user.id&&productIds.includes(p.id));if(ownProducts.length!==productIds.length)throw Error('Um ou mais produtos não pertencem a esta conta.');const ownGroups=groups.filter(g=>g.userId===req.user.id&&groupIds.includes(g.id));if(ownGroups.length!==groupIds.length)throw Error('Um ou mais grupos não pertencem a esta conta.');if(ownGroups.some(g=>!g.jid))throw Error('Um ou mais grupos ainda não estão vinculados ao WhatsApp. Conecte o WhatsApp e tente novamente.');assertQuota(req.user.id,productIds);const when=new Date(req.body.scheduledAt);if(!Number.isFinite(when.getTime()))throw Error('Data/horário inválidos');const freq=['once','daily','weekly'].includes(req.body.frequency)?req.body.frequency:'once';const j={id:crypto.randomUUID(),userId:req.user.id,productIds,groupIds,scheduledAt:when.toISOString(),frequency:freq,enabled:true,status:'pending',sentCount:0,messageTemplate:String(req.body.messageTemplate||'')};jobs.push(j);save(files.jobs,jobs);log('job_created',req.user.id,{jobId:j.id,productIds,groupIds});res.json({ok:true,job:j,quota:quota(req.user.id)})}catch(e){res.status(400).json({error:e.message})}});
app.patch('/api/jobs/:id',(req,res)=>{try{const j=jobs.find(x=>x.id===req.params.id&&x.userId===req.user.id);if(!j)return res.status(404).json({error:'Agendamento não encontrado'});const next={...j,...req.body};const productIds=[...new Set(jobProductIds(next).filter(Boolean).map(String))],groupIds=[...new Set((Array.isArray(next.groupIds)?next.groupIds:[next.groupId]).filter(Boolean).map(String))];if(!productIds.length||!groupIds.length)throw Error('Agendamento precisa de produto e grupo.');if(products.filter(p=>p.userId===req.user.id&&productIds.includes(p.id)).length!==productIds.length)throw Error('Produto inválido para esta conta.');if(groups.filter(g=>g.userId===req.user.id&&groupIds.includes(g.id)).length!==groupIds.length)throw Error('Grupo inválido para esta conta.');if(groups.filter(g=>g.userId===req.user.id&&groupIds.includes(g.id)).some(g=>!g.jid))throw Error('Grupo ainda não vinculado ao WhatsApp.');if(next.enabled!==false)assertQuota(req.user.id,productIds);Object.assign(j,next,{productIds,groupIds});save(files.jobs,jobs);res.json({ok:true,job:j,quota:quota(req.user.id)})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/jobs/:id',(req,res)=>{jobs=jobs.filter(x=>!(x.id===req.params.id&&x.userId===req.user.id));save(files.jobs,jobs);res.json({ok:true})});
async function sendOne(uid,j,p,g){const x=wa.get(uid);if(!x?.sock||x.state!=='connected')throw Error('WhatsApp desconectado');const text=renderMsg(j.messageTemplate||p.message||templates[0].text,p);if(p.imageData){const m=String(p.imageData).match(/^data:(.+?);base64,(.*)$/);if(m)await x.sock.sendMessage(g.jid,{image:Buffer.from(m[2],'base64'),caption:text});else if(p.imageUrl)await x.sock.sendMessage(g.jid,{image:{url:p.imageUrl},caption:text});else await x.sock.sendMessage(g.jid,{text})}else if(p.imageUrl){await x.sock.sendMessage(g.jid,{image:{url:p.imageUrl},caption:text})}else await x.sock.sendMessage(g.jid,{text});j.sentCount=(j.sentCount||0)+1}
async function processJobs(){const now=Date.now();for(const j of jobs.filter(x=>x.enabled!==false&&x.status==='pending')){if(new Date(j.scheduledAt).getTime()>now)continue;const gs=groups.filter(g=>g.userId===j.userId&&(j.groupIds||[]).includes(g.id));const ps=products.filter(p=>p.userId===j.userId&&(j.productIds||[]).includes(p.id));try{for(const p of ps)for(const g of gs)await sendOne(j.userId,j,p,g);if(j.frequency==='once'){j.status='sent';j.enabled=false}else if(j.frequency==='daily'){j.scheduledAt=new Date(new Date(j.scheduledAt).getTime()+864e5).toISOString()}else if(j.frequency==='weekly'){j.scheduledAt=new Date(new Date(j.scheduledAt).getTime()+7*864e5).toISOString()}else {j.status='sent';j.enabled=false}}catch(e){j.error=e.message;j.status='error'}}save(files.jobs,jobs)}
cron.schedule('* * * * *',()=>processJobs().catch(e=>console.error(e)),{timezone:TZ});
cron.schedule('*/5 * * * *',()=>{let changed=false;for(const s of db.subscriptions){if(s.status==='active'&&new Date(s.expiresAt)<=new Date()){s.status='expired';changed=true;log('subscription_expired',s.userId)}}if(changed)save(files.db,db)},{timezone:TZ});


app.post('/api/subscription/select',(req,res)=>{try{const p=db.plans.find(x=>x.id===req.body?.planId);if(!p)throw Error('Plano não encontrado');let s=subOf(req.user.id);if(!s){s={id:crypto.randomUUID(),userId:req.user.id,status:'pending'};db.subscriptions.push(s)}s.requestedPlanId=p.id;s.requestedPlanName=p.name;s.requestedAt=new Date().toISOString();save(files.db,db);log('subscription_plan_selected',req.user.id,{planId:p.id});res.json({ok:true,plan:p,subscription:s})}catch(e){res.status(400).json({error:e.message})}});
app.delete('/api/groups/:id',(req,res)=>{groups=groups.filter(g=>!(g.id===req.params.id&&g.userId===req.user.id));save(files.groups,groups);res.json({ok:true})});
app.post('/api/jobs/:id/send',async(req,res)=>{const j=jobs.find(x=>x.id===req.params.id&&x.userId===req.user.id);if(!j)return res.status(404).json({error:'Agendamento não encontrado'});try{if(!activeSub(req.user.id))throw Error('Assinatura vencida ou inativa.');const gs=groups.filter(g=>g.userId===req.user.id&&(j.groupIds||[]).includes(g.id));const ps=products.filter(p=>p.userId===req.user.id&&(j.productIds||[]).includes(p.id));if(!gs.length||!ps.length)throw Error('Selecione pelo menos um produto e um grupo');for(const p of ps)for(const g of gs)await sendOne(req.user.id,j,p,g);j.status='sent';j.enabled=false;j.sentAt=new Date().toISOString();save(files.jobs,jobs);log('job_sent_now',req.user.id,{jobId:j.id});res.json({ok:true,job:j})}catch(e){j.status='error';j.error=e.message;save(files.jobs,jobs);res.status(400).json({error:e.message,job:j})}});
app.post('/api/payments/webhook',(req,res)=>{const secret=req.headers['x-webhook-secret']||'';if(process.env.PAYMENT_WEBHOOK_SECRET&&secret!==process.env.PAYMENT_WEBHOOK_SECRET)return res.status(401).json({error:'Webhook não autorizado'});const {userId,status,planId,paymentId}=req.body||{};const u=db.users.find(x=>x.id===userId);if(!u)return res.status(404).json({error:'Cliente não encontrado'});let s=subOf(userId);if(!s){s={id:crypto.randomUUID(),userId};db.subscriptions.push(s)}if(status==='approved'||status==='paid'||status==='confirmed'){const base=new Date(s.expiresAt)>new Date()?new Date(s.expiresAt):new Date();s.status='active';s.planId=planId||s.planId||'p1';s.startedAt=new Date().toISOString();s.expiresAt=new Date(base.getTime()+30*864e5).toISOString();u.active=true;s.paymentId=paymentId||'';log('payment_confirmed','system',{userId,planId,paymentId})}save(files.db,db);res.json({ok:true,subscription:s})});
app.use(express.static(path.join(process.cwd(),'public')));app.get('/',(_,res)=>res.sendFile(path.join(process.cwd(),'public','index.html')));app.get('/*splat',(_,res)=>res.sendFile(path.join(process.cwd(),'public','index.html')));
await initPersistence();
ensureMaster();
if(pool) await persistState();
app.listen(PORT,'0.0.0.0',()=>{console.log(`OfertaZap SaaS V38 na porta ${PORT}`);console.log(`DATA_DIR=${ROOT}`);console.log(`AUTH_ROOT=${AUTH_ROOT}`);console.log(`POSTGRES=${pool?'connected':'not configured'}`);for(const u of db.users.filter(x=>x.role==='CLIENT'&&x.active!==false)){if(activeSub(u.id))startWA(u.id).catch(e=>console.error('WA',u.id,e.message))}});
